### PR TITLE
Fraud hosted fields

### PR DESCRIPTION
**Pull request by hectoregm**
This PR gets the device_data to enable fraud detection from Braintree. We pass the device_data
at creation of payment profile and in the confirmation of the order.

Built ontop of #29, same flow as in #28 but with better error handling for hosted fields.

### CODE REVIEW

**Comment by jhawthorn** [comment]
Thanks for this work @hectoregm. This is definitely some thing we want to include.

My one concern is that this is a little bit invasive. This adds the `device_data` attr to both `Order` and `Payment` and overrides both `unprocessed_payments` and `OrderUpdateAttributes#apply`.

What if instead we add `device_data` just to `Order` and add a module prepend to `Payment::Processing#gateway_options` to add the order's device_data to the options. This should be simpler (half the overrides), and `gateway_options` is already a well used extension point.

**Comment by hectoregm** [comment]
I tried that but order is loaded from DB before gateway_option so the temporary device_data is not
present in gateway_options

**Comment by hectoregm** [comment]
@jhawthorn I believe the only other option is to add a column to order so the device_data can be retrieve at any moment

**Comment by hectoregm** [comment]
Added the data attribute, and override of gateway_options is now more clean and simple.

**Comment by jhawthorn** [comment]
Are you sure it doesn't work as an `attr_accessor`, I did a quick test and all specs still passed.

**Comment by hectoregm** [comment]
Added a test to show that a `attr_accessor` is not enough.

**Comment by jhawthorn** [comment]
Thanks @hectoregm that spec is extremely helpful.

The reason it needs to be saved is that the `inverse_of` from a payment back to its order is missing. I'll work on adding that to solidus and then maybe we can drop the `braintree_device_data` column in a future version.

**Pull request merged**
