### PR TITLE
Add AVS response code to ActiveMerchant responses

### PR DESCRIPTION
**Pull request by philbirt**
This will also allow payment processing to store AVS codes on the `Spree::Payment` model.

### CODE REVIEW

**Comment by philbirt** [comment]
@athal7 would you mind taking a look at this today?

**Comment by athal7** [comment]
:+1:

Some non-blocking comments:
- The options_from_results method is a bit vague, I wonder if we need to have an empty has vs keys with nil values?
- Would be interested to see some failure case specs, or maybe an assertion around the value as opposed to just the presence
- Here's a fun implementation idea for the options method: 
```ruby
{}.tap do |opts|
  opts.merge!(authorization: result.transaction.id, avs_result: { code: result.transaction.avs_street_address_response_code }) if result.success?
end
```

**Comment by philbirt** [comment]
* Added assertions against the value instead of presence
* Tap tap tap
* Renamed the method to "build_results_hash" which i think is a bit more explanatory of what its doing

What do you think?

**Comment by athal7** [comment]
👍

**Comment by athal7** [comment]
I like the new method name too

**Comment by jhawthorn** [comment]
Merged as #18

**Pull request closed without merging**
